### ISSUE TITLE
TypeError: this.sizes.then is not a function

### ISSUE THREAD

**Issue by felixfbecker** [GoogleChromeLabs/size-plugin#7]
Getting this when running webpack in watch mode:
```
TypeError: this.sizes.then is not a function
    at SizePlugin.<anonymous> (node_modules/size-plugin/src/index.mjs:91:23)
    at new Promise (<anonymous>)
    at SizePlugin.outputSizes (node_modules/size-plugin/dist/size-plugin.js:81:12)
    at node_modules/size-plugin/src/index.mjs:86:65
    at AsyncSeriesHook.eval [as callAsync] (eval at create (node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:8:1)
    at asyncLib.forEach.err (node_modules/webpack/lib/Compiler.js:355:27)
    at done (node_modules/neo-async/async.js:2854:11)
    at node_modules/neo-async/async.js:2805:7
    at MemoryFileSystem.writeFile (node_modules/memory-fs/lib/MemoryFileSystem.js:328:9)
    at writeOut (node_modules/webpack/lib/Compiler.js:339:29)
    at Immediate.<anonymous> (node_modules/memory-fs/lib/MemoryFileSystem.js:288:4)
    at runCallback (timers.js:693:18)
    at tryOnImmediate (timers.js:664:5)
    at processImmediate (timers.js:646:5)
    at process.topLevelDomainCallback (domain.js:121:23)
```
Using thread-loader, webpack-serve, ts-loader, ExtractTextPlugin and a few others. Not sure if relevant.

**Comment by developit** [comment]
Hi @felixfbecker - what version of webpack are you running?
